import gzip
import json
import os
from dataclasses import dataclass
from datetime import UTC, datetime
from importlib.resources import files
from pathlib import Path
from typing import Any

import duckdb
import geopandas as gpd
import pandas as pd

from single_stair.transform.clean_and_join import latest_snapshot
from single_stair.zoning_filters import (
    coverage_area_geojson,
    coverage_parcel_geojson,
    current_zoning_config,
    current_zoning_geojson,
    read_boundaries,
    read_coverage_parcels,
)


@dataclass(frozen=True, slots=True)
class VisualizationExport:
    output_directory: Path
    candidate_count: int
    neighborhood_count: int
    ward_count: int
    community_area_count: int


def _write_json(path: Path, payload: Any, *, compressed: bool = False) -> None:
    serialized = json.dumps(payload, separators=(",", ":"), ensure_ascii=False)
    if compressed:
        with gzip.open(path, "wt", encoding="utf-8", compresslevel=9) as output:
            output.write(serialized)
    else:
        path.write_text(serialized + "\n", encoding="utf-8")


def write_visualization_config(output: Path = Path("web/config.js")) -> Path:
    """Generate only public map settings; never serialize the full environment."""
    config = {
        "protomapsApiKey": os.environ.get("PROTOMAPS_API_KEY", ""),
        "protomapsUrl": os.environ.get("PROTOMAPS_URL", ""),
    }
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        "// Generated by single-stair visualize configure. Do not edit or commit.\n"
        f"window.SINGLE_STAIR_CONFIG = {json.dumps(config, ensure_ascii=True)};\n",
        encoding="utf-8",
    )
    return output


def _candidate_query() -> str:
    return """
        SELECT objectid, pin, centroid_lon, centroid_lat,
               community_area_name, canonical_zone_class, upzoned_zone_class,
               transit_distance_ft, nearest_transit_agency,
               is_city_owned, is_vacant, is_underbuilt,
               requires_legal_or_site_review, review_reasons,
               median_need_score, median_need_high_need_low_supply,
               current_two_stair_three_bedroom_capacity,
               current_single_stair_three_bedroom_capacity,
               upzoned_single_stair_three_bedroom_capacity
        FROM read_parquet(?, union_by_name=true)
        WHERE has_any_modeled_capacity
          AND (is_city_owned OR is_vacant OR is_underbuilt)
          AND centroid_lon IS NOT NULL AND centroid_lat IS NOT NULL
    """


def _candidate_geojson(connection: duckdb.DuckDBPyConnection, source: Path) -> dict[str, Any]:
    rows = connection.execute(_candidate_query(), [str(source / "part-*.parquet")]).fetchall()
    features = []
    for row in rows:
        (
            objectid,
            pin,
            longitude,
            latitude,
            community,
            zoning,
            upzoned_zoning,
            transit_distance,
            transit_agency,
            city_owned,
            vacant,
            underbuilt,
            requires_review,
            review_reasons,
            need_score,
            high_need,
            current_two_stair,
            current_single_stair,
            upzoned_single_stair,
        ) = row
        features.append(
            {
                "type": "Feature",
                "id": objectid,
                "geometry": {"type": "Point", "coordinates": [longitude, latitude]},
                "properties": {
                    "pin": pin,
                    "community": community,
                    "zoning": zoning,
                    "upzoned_zoning": upzoned_zoning,
                    "transit_distance_ft": transit_distance,
                    "transit_agency": transit_agency,
                    "city_owned": bool(city_owned),
                    "vacant": bool(vacant),
                    "underbuilt": bool(underbuilt),
                    "requires_review": bool(requires_review),
                    "review_reasons": review_reasons,
                    "need_score": need_score,
                    "high_need_low_supply": bool(high_need),
                    "current_two_stair": current_two_stair,
                    "current_single_stair": current_single_stair,
                    "upzoned_single_stair": upzoned_single_stair,
                },
            }
        )
    return {"type": "FeatureCollection", "features": features}


def _neighborhood_rows(connection: duckdb.DuckDBPyConnection, source: Path) -> list[dict[str, Any]]:
    query = """
        WITH tract_community_counts AS (
            SELECT census_tract_geoid, community_area_number, community_area_name, count(*) parcels
            FROM read_parquet(?, union_by_name=true)
            WHERE census_tract_geoid IS NOT NULL AND community_area_name IS NOT NULL
            GROUP BY ALL
        ), tract_community AS (
            SELECT * EXCLUDE(parcels)
            FROM tract_community_counts
            QUALIFY row_number() OVER (
                PARTITION BY census_tract_geoid
                ORDER BY parcels DESC, community_area_number
            ) = 1
        ), tract_metrics AS (
            SELECT census_tract_geoid,
                   max(family_housing_3_plus_gap_conservative_estimate) gap_conservative,
                   max(family_housing_3_plus_gap_median_estimate) gap_median,
                   max(family_housing_3_plus_gap_progressive_estimate) gap_progressive,
                   max(median_need_score) need_score
            FROM read_parquet(?, union_by_name=true)
            WHERE census_tract_geoid IS NOT NULL
            GROUP BY 1
        )
        SELECT community_area_number, community_area_name,
               count(*) tract_count,
               sum(gap_conservative) gap_conservative,
               sum(gap_median) gap_median,
               sum(gap_progressive) gap_progressive,
               avg(need_score) mean_need_score
        FROM tract_community JOIN tract_metrics USING (census_tract_geoid)
        GROUP BY 1, 2
        ORDER BY gap_median DESC NULLS LAST, community_area_number
    """
    pattern = str(source / "part-*.parquet")
    frame = connection.execute(query, [pattern, pattern]).fetchdf()
    return frame.where(frame.notna(), None).to_dict(orient="records")


def _comparison_rows(connection: duckdb.DuckDBPyConnection, source: Path) -> list[dict[str, Any]]:
    query = """
        SELECT community_area_number, community_area_name, capacity_scenario_id,
               modeled_capacity_units, incremental_capacity_vs_current_two_stair_units,
               parcel_count, requires_legal_or_site_review_parcel_count
        FROM read_parquet(?, union_by_name=true)
        WHERE bedroom_category = 'three_bedroom'
        ORDER BY community_area_number, capacity_scenario_id
    """
    frame = connection.execute(query, [str(source / "part-*.parquet")]).fetchdf()
    return frame.where(frame.notna(), None).to_dict(orient="records")


def _summary_geojson(
    boundary_source: Path,
    summary_source: Path,
    *,
    boundary_key: str,
    summary_key: str,
    geography_key: str,
    boundary_name: str | None = None,
    geography_name: str | None = None,
) -> dict[str, Any]:
    boundary_parts = sorted(boundary_source.glob("part-*.parquet"))
    if not boundary_parts:
        raise FileNotFoundError(f"Boundary snapshot has no Parquet parts: {boundary_source}")
    boundary_frames = [gpd.read_parquet(part) for part in boundary_parts]
    boundaries = gpd.GeoDataFrame(
        pd.concat(boundary_frames, ignore_index=True),
        geometry="geometry",
        crs=boundary_frames[0].crs,
    ).to_crs("EPSG:4326")
    boundary_renames = {boundary_key: geography_key}
    boundary_columns = [boundary_key, "geometry"]
    if boundary_name and geography_name:
        boundary_renames[boundary_name] = geography_name
        boundary_columns.insert(1, boundary_name)
    boundaries = boundaries[boundary_columns].rename(columns=boundary_renames)
    boundaries[geography_key] = boundaries[geography_key].astype("string")

    connection = duckdb.connect()
    query = f"""
        SELECT {summary_key} AS geography_key, capacity_scenario_id,
               modeled_capacity_units,
               incremental_capacity_vs_current_two_stair_units,
               capacity_gain_parcel_count,
               requires_legal_or_site_review_parcel_count
        FROM read_parquet(?, union_by_name=true)
        WHERE bedroom_category = 'three_bedroom'
    """
    summary = connection.execute(query, [str(summary_source / "part-*.parquet")]).fetchdf()
    summary["geography_key"] = summary["geography_key"].astype("string")
    metrics = summary.pivot(index="geography_key", columns="capacity_scenario_id").reset_index()
    metrics.columns = [
        geography_key if column == ("geography_key", "") else f"{column[1]}_{column[0]}"
        for column in metrics.columns
    ]
    geographies = boundaries.merge(metrics, on=geography_key, how="left", validate="one_to_one")
    return json.loads(geographies.to_json(drop_id=True))


def _ward_geojson(boundary_source: Path, summary_source: Path) -> dict[str, Any]:
    return _summary_geojson(
        boundary_source,
        summary_source,
        boundary_key="ward",
        summary_key="ward",
        geography_key="ward",
    )


def _community_area_geojson(boundary_source: Path, summary_source: Path) -> dict[str, Any]:
    return _summary_geojson(
        boundary_source,
        summary_source,
        boundary_key="area_numbe",
        summary_key="community_area_number",
        geography_key="community_area_number",
        boundary_name="community",
        geography_name="community_area_name",
    )


def export_visualization_data(
    *,
    raw_root: Path = Path("data/raw"),
    final_root: Path = Path("data/final"),
    output_directory: Path = Path("web/data"),
    policy_id: str = "chicago_proposed",
    estimate_id: str = "median",
) -> VisualizationExport:
    parcel_dataset = f"parcel_opportunity_with_need_{policy_id}_{estimate_id}"
    community_dataset = f"opportunity_need_by_community_area_{policy_id}_{estimate_id}"
    ward_dataset = f"opportunity_need_by_ward_{policy_id}_{estimate_id}"
    parcel_source = latest_snapshot(final_root, parcel_dataset)
    community_source = latest_snapshot(final_root, community_dataset)
    ward_source = latest_snapshot(final_root, ward_dataset)
    ward_boundary_source = latest_snapshot(raw_root, "chicago_ward_boundaries")
    community_boundary_source = latest_snapshot(raw_root, "chicago_community_area_boundaries")
    zoning_source = latest_snapshot(raw_root, "chicago_zoning")
    output_directory.mkdir(parents=True, exist_ok=True)
    connection = duckdb.connect()
    candidates = _candidate_geojson(connection, parcel_source)
    neighborhoods = _neighborhood_rows(connection, parcel_source)
    comparisons = _comparison_rows(connection, community_source)
    wards = _ward_geojson(ward_boundary_source, ward_source)
    community_areas = _community_area_geojson(community_boundary_source, community_source)
    scenario_config = json.loads(
        files("single_stair").joinpath("config/building_scenarios.v1.json").read_text("utf-8")
    )
    map_scenarios = [current_zoning_config()]
    map_scenario_ids = [scenario["id"] for scenario in map_scenarios]
    coverage = read_coverage_parcels(parcel_source)
    coverage_points = coverage_parcel_geojson(coverage, map_scenario_ids)
    zoning_coverage = current_zoning_geojson(zoning_source)
    coverage_wards = coverage_area_geojson(
        read_boundaries(ward_boundary_source),
        coverage,
        map_scenario_ids,
        boundary_key="ward",
        parcel_key="ward",
    )
    coverage_communities = coverage_area_geojson(
        read_boundaries(community_boundary_source),
        coverage,
        map_scenario_ids,
        boundary_key="area_numbe",
        parcel_key="community_area_number",
        boundary_name="community",
    )
    _write_json(output_directory / "coverage_parcels.geojson.gz", coverage_points, compressed=True)
    _write_json(output_directory / "zoning_coverage.geojson.gz", zoning_coverage, compressed=True)
    _write_json(output_directory / "coverage_wards.geojson", coverage_wards)
    _write_json(output_directory / "coverage_community_areas.geojson", coverage_communities)
    _write_json(output_directory / "candidates.geojson.gz", candidates, compressed=True)
    _write_json(output_directory / "neighborhoods.json", neighborhoods)
    _write_json(output_directory / "comparisons.json", comparisons)
    _write_json(output_directory / "wards.geojson", wards)
    _write_json(output_directory / "community_areas.geojson", community_areas)
    _write_json(
        output_directory / "metadata.json",
        {
            "generated_at": datetime.now(UTC).isoformat(),
            "map_schema_version": 2,
            "map_scenarios": map_scenarios,
            "map_parcel_count": len(coverage_points["features"]),
            "map_definition": (
                "Selected zoning coverage, not legal single-stair eligibility or a unit forecast. "
                "Overview counts include all matching source parcel records regardless of "
                "capacity, vacancy, ownership, or underbuilt status. "
                "Records are not unique development sites."
            ),
            "map_grain": {
                "parcels": "One source parcel objectid, shown at its centroid",
                "zoning": "One city zoning objectid, original polygon geometry",
                "wards": "One official ward; parcel records assigned by centroid",
                "community_areas": "One official community area; records assigned by centroid",
            },
            "map_coverage_counts": {
                scenario: {
                    "parcel_records": int(coverage[scenario].sum()),
                    "missing_centroid": int(
                        (
                            coverage[scenario]
                            & (coverage.centroid_lon.isna() | coverage.centroid_lat.isna())
                        ).sum()
                    ),
                    "unassigned_ward": int((coverage[scenario] & coverage.ward.isna()).sum()),
                    "unassigned_community_area": int(
                        (coverage[scenario] & coverage.community_area_number.isna()).sum()
                    ),
                }
                for scenario in map_scenario_ids
            },
            "policy_id": policy_id,
            "estimate_id": estimate_id,
            "candidate_definition": (
                "Modeled parcel independently flagged vacant, underbuilt, or city-owned"
            ),
            "candidate_geometry": "parcel centroid",
            "candidate_count": len(candidates["features"]),
            "neighborhood_count": len(neighborhoods),
            "ward_count": len(wards["features"]),
            "community_area_count": len(community_areas["features"]),
            "source_snapshots": [
                str(parcel_source),
                str(community_source),
                str(ward_source),
                str(ward_boundary_source),
                str(community_boundary_source),
                str(zoning_source),
            ],
            "scenarios": scenario_config,
            "limitations": [
                "Capacity is analytical and is not a legal or architectural determination.",
                "Candidate flags are independent screens, not a composite ranking.",
                (
                    "Neighborhood need assigns each tract to the community area containing "
                    "the plurality of analyzed parcel centroids."
                ),
            ],
        },
    )
    return VisualizationExport(
        output_directory,
        len(candidates["features"]),
        len(neighborhoods),
        len(wards["features"]),
        len(community_areas["features"]),
    )
